---
- name: Installing tomcat, copying the tomcat-users.xml, replace the port number, restarting the service, validating the url
  hosts: all
  tasks:
    - name: install tomcat
      apt:
        name: tomcat10
        state: present
        update_cache: yes
    - name: install tomcat10-admin
      apt:
        name: tomcat10-admin
        state: present
    - name: copying tomcat-users.xml
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: replacing the port number from 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: restarting the tomcat10 service
      service:
        name: tomcat10
        state: restarted
    - name: Pause for 60 sec to complete restart
      pause:
        seconds: 60
    - name: validating server1 tomcat10 application
      uri:
        url: http://50.18.141.89:9090
        status_code: 200
    - name: validating the tomcat10-admin service
      uri:
        url: http://13.52.163.139:9090
        status_code: 200
...
