---
 - name: installing multiple s/w
   hosts: all
   tasks:
     - name: installing s/w
       apt:
         name: "{{item.a}}"
         state: "{{item.b}}"
         update_cache: "{{item.c}}"
       with_items:
         - {a: git,b: present,c: yes}
         - {a: maven,b: present,c: yes}
         - {a: openjdk-17-jdk,b: present,c: yes}
...
