---
 - name: Implementing handlers
   hosts: all
   tasks:
     - name: installing apache2
       apt:
         name: apache2
         state: present
         update_cache: yes
       notify: Restart apache2
     - name: Changing the content in front page
       copy:
         content: welcome to apache2!!"
         dest: /var/www/html/index.html
       notify: Restart apache2
   handlers:
     - name: Restart apache2
       service:
         name: apache2
         state: restarted
     - name: Checking the apache2 url
       uri:
         url: "{{item}}"
         status_code: 200
       with_items:
         - http://172.31.13.87
         - http://172.31.1.109
...
