---
 - name: installing tomcat10 and tomcat10-admin
   hosts: all
   tasks:
     - name: installing the s/w
       apt:
         name: "{{item.a}}"
         state: "{{item.b}}"
         update_cache: "{{item.c}}"
       with_items:
         - {a: tomcat10,b: present,c: yes}
         - {a: tomcat10-admin,b: present, c: no}
     - name: copying the tomcat-users.xml file
       copy:
         src: tomcat-users.xml
         dest: /etc/tomcat10
     - name: replacing the port number from 8080 to 9090
       replace:
         regexp: 8080
         replace: 9090
         path: /etc/tomcat10/server.xml
     - name: Restart the service
       service:
         name: tomcat10
         state: restarted
     - name: Waiting until restart is complete
       pause:
         seconds: 60
     - name: Validating the url
       uri:
         url: "{{item}}"
         status_code: 200
       with_items:
         - http://172.31.13.87:9090
         - http://172.31.1.109:9090

...

