---
- name: Implementing tags
  hosts: all
  gather_facts: false
  become: yes
  tasks:  
    - name: installing tree software
      apt:
        name: tree
        state: present
        update_cache: yes
      tags: 
        - tree_installation
        - always
    - name: Creating a user
      user:
        name: Anu
        password: Anu
      tags: user_creation
    - name: Copying the passwd file
      copy:
        src: /etc/passwd
        dest: /tmp
...
