---
 - name: creating a directory and downloading the jenkins.war
   hosts: all
   tasks: 
     - name: creating a directory
       file:
         name: /tmp/newfolder
         state: directory
     - name: downloading the file Jenkins.war
       get_url:
         url: https://get.jenkins.io/war-stable/2.504.2/jenkins.war
         dest: /tmp/newfolder
...           
