---
 - name: installing tree software on ubuntu servers
   hosts: ubuntuservers
   tasks:
     - name: installing the tree software
       apt:
         name: tree
         state: present
         update_cache: yes
 - name: installing tree software on redhat servers
   hosts: redhatservers
   tasks:
     - name: installing the tree software
       yum:
         name: tree
         state: present
         update_cache: yes
...
